import { HttpException, Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { Prisma } from '@prisma/client';

@Injectable()
export class UsersService {
  // eslint-disable-next-line prettier/prettier
  constructor(private prisma: PrismaService) { }

  // Prisma.UserCreateInput is generated by Prisma
  createUser(data: Prisma.UserCreateInput) {
    return this.prisma.user.create({
      data: {
        ...data,
        UserSetting: {
          create: {
            smsEnabled: true,
            notificationsOn: false,
          },
        },
      },
    });
  }

  getUsers() {
    return this.prisma.user.findMany({
      include: {
        UserSetting: {
          select: {
            smsEnabled: true,
            notificationsOn: true,
          },
        },
        posts: {
          select: {
            id: true,
          },
        },
        groupPosts: true,
      },
    });
  }

  getUsersById(id: number) {
    return this.prisma.user.findUnique({
      where: { id },
      include: {
        UserSetting: {
          select: {
            smsEnabled: true,
            notificationsOn: true,
          },
        },
        posts: true,
        groupPosts: true,
      },
    });
  }

  async updateUserById(id: number, data: Prisma.UserUpdateInput) {
    const findUser = await this.getUsersById(id);
    if (!findUser) throw new HttpException('User not found', 400);
    if (data.username) {
      const findUser = await this.prisma.user.findUnique({
        where: { username: data.username as string },
      });
      if (findUser) throw new HttpException('Username already taken', 400);
    }
    return this.prisma.user.update({ where: { id }, data });
  }

  async deleteUserById(id: number) {
    const findUser = await this.getUsersById(id);
    if (!findUser) throw new HttpException('User not found', 400);
    return this.prisma.user.delete({ where: { id } });
  }

  async updateSettingsByUserId(
    userId: number,
    data: Prisma.UserSettingUpdateInput,
  ) {
    const findUser = await this.getUsersById(userId);
    if (!findUser) throw new HttpException('User not found', 400);
    if (!findUser.UserSetting) throw new HttpException('Not Settings', 400);
    return this.prisma.userSetting.update({ where: { userId }, data });
  }
}
